### ISSUE TITLE
modernizr offers bower builds

### ISSUE THREAD

**Issue by patrickkettner** [psullivan6/Modernizr#1]
just a heads up, you can use Modernizr for a bower server, just add .zip to the end of your build

bower install --save http://modernizr.com/download/?-serviceworker-touchevents.zip

**Comment by psullivan6** [comment]
I should have known this, duhh. Thanks for pointing it out :+1:

**Comment by psullivan6** [comment]
I just tested and seems like:

`bower install https://modernizr.com/download\?serviceworker-touchevents --save` worked fine, so `.zip` wasn't needed
